---
- name: Start 'kopia'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'kopia'
    t_app_data_dirs:
      - '{{ p_apps_data }}/kopia/config'
      - '{{ p_apps_data }}/kopia/cache'
      - '{{ p_apps_data }}/kopia/logs'
      - '{{ p_apps_data }}/kopia/rclone'
      - '{{ p_apps_data }}/kopia/mounts'
      - '{{ p_backups_root }}/kopia/repositiory'
  tags:
    - kopia

- name: Configure 'rclone'
  ansible.builtin.template:
    src: rclone.conf.j2
    dest: "{{ p_apps_data }}/kopia/rclone/rclone.conf"
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - kopia

- name: Run a simple command (argv)
  community.docker.docker_container_exec:
    container: backrest
    argv:
      - /bin/bash
      - "-c"
      - "sudo -v ; curl https://rclone.org/install.sh | sudo bash"
    chdir: /root
  register: result

- name: Print stderr lines
  ansible.builtin.debug:
    var: result.stderr_lines

- name: Print stdout lines
  ansible.builtin.debug:
    var: result.stdout_lines
