---
- name: Start 'grist'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'grist'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/grist/grist'
      - '{{ p_dirs.apps_data }}/grist/redis'
      - '{{ p_dirs.apps_data }}/grist/minio'

- name: Add Python libs into Grist
  community.docker.docker_container_exec:
    container: grist_app
    user: root
    argv:
      - /bin/bash
      - "-c"
      - "apt update && apt install -y openssl && python3 -m pip install numpy holidays"
  register: result

- name: Print stdout lines
  ansible.builtin.debug:
    var: result.stdout_lines

- name: Print stderr lines
  ansible.builtin.debug:
    var: result.stderr_lines
