---
- name: Free '53' port from 'systemd-resolved'
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#DNSStubListener=.*$'
    line: 'DNSStubListener=no'
  become: true

- name: Restart 'systemd-resolved'
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  become: true

- name: Pre-create log directory
  ansible.builtin.file:
    path: '{{ p_dirs.apps_data }}/pihole/var-log'
    state: directory
    owner: '{{ p_apps_user.user }}'
    group: '{{ p_apps_user.group }}'
    recurse: true
    mode: '{{ p_default_permissions.directory }}'
  become: true

- name: Pre-create log file
  ansible.builtin.file:
    path: '{{ p_dirs.apps_data }}/pihole/var-log/pihole.log'
    state: touch
    owner: '{{ p_apps_user.user }}'
    group: '{{ p_apps_user.group }}'
    mode: '{{ p_default_permissions.file }}'
  become: true

- name: Start 'Pi-Hole'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'pihole'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/pihole/etc-pihole'
      - '{{ p_dirs.apps_data }}/pihole/etc-dnsmasq.d'
