---
- name: Create directory for the app's data
  ansible.builtin.file:
    path: '{{ dir_path }}'
    state: directory
    owner: '{{ p_apps_user.user }}'
    group: '{{ p_apps_user.group }}'
    recurse: true
    mode: '{{ p_default_permissions.directory }}'
  become: true
  loop:
    - '{{ p_dirs.apps_data }}/opencloud/config'
    - '{{ p_dirs.apps_data }}/opencloud/apps'
    - '{{ p_dirs.slow_data }}/opencloud/data'
  loop_control:
    loop_var: dir_path

- name: Copy csp.yaml file
  ansible.builtin.template:
    src: csp.yaml.j2
    dest: '{{ p_dirs.apps_data }}/opencloud/config/csp.yaml'
    owner: '{{ p_apps_user.user }}'
    group: '{{ p_apps_user.group }}'
    mode: '{{ p_default_permissions.file }}'
  become: true

- name: Copy app-registry.yaml file
  ansible.builtin.copy:
    src: app-registry.yaml
    dest: '{{ p_dirs.apps_data }}/opencloud/config/app-registry.yaml'
    owner: '{{ p_apps_user.user }}'
    group: '{{ p_apps_user.group }}'
    mode: '{{ p_default_permissions.file }}'
  become: true

- name: Start 'opencloud'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'opencloud'
