---
- name: Start 'immich'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'immich'
    t_app_data_dirs:
      - '{{ imch_apps_data_path }}/immich/db'
      - '{{ imch_apps_data_path }}/immich/model-cache'
      - '{{ imch_store_data_path }}/immich/upload'
