---
- name: Configure the home server
  hosts: homeserver
  vars_files:
    - vars/vault.yml
  vars:
    p_apps_data: '{{ g_pools.fast.custom_dirs.apps_data }}'
    p_apps_user: '{{ g_apps_user }}'
  tasks:
    - name: Setup environment
      ansible.builtin.include_tasks: tasks/setup_environment.yml
      tags:
        - server_init

    - name: Setup observability
      ansible.builtin.include_role:
        name: setup_observability
      vars:
        obs_app_user: '{{ p_apps_user }}'
        obs_apps_data_path: '{{ p_apps_data }}'
      tags:
        - applications
        - observability

    - name: Deploy 'dockge'
      ansible.builtin.include_role:
        name: deploy_dockge
      vars:
        dkg_apps_data_path: '{{ p_apps_data }}'
        dkg_stack_path: '{{ g_pools.fast.custom_dirs.compose_files }}'
        dkg_app_user: '{{ p_apps_user }}'
      tags:
        - applications
        - dockge

    - name: Deploy 'immich'
      ansible.builtin.include_role:
        name: deploy_immich
      vars:
        imch_apps_data_path: '{{ p_apps_data }}'
        imch_store_data_path: '{{ g_pools.slow.custom_dirs.apps_data }}'
        imch_app_version: v1.92.1
        imch_app_user: '{{ p_apps_user }}'
        imch_db_password: '{{ g_db_passwords.immich }}'
      tags:
        - applications
        - immich
