---
- name: Configure the home server
  hosts: homeserver
  vars_files:
    - vars/vault.yml
    - vars/apps.yml
  vars:
    p_timezone: '{{ g_timezone }}'

    p_apps_data: '{{ g_pools.fast.custom_dirs.apps_data }}'
    p_compose_files: '{{ g_pools.fast.custom_dirs.compose_files }}'
    p_backups_root: '{{ g_pools.slow.custom_dirs.backups_root }}'

    p_apps_user: '{{ g_apps_user }}'

    p_default_permissions:
      file: '0644'
      directory: '0754'
  tasks:
    - name: Setup environment
      ansible.builtin.include_tasks: tasks/setup_environment.yml
      tags:
        - server_init

    - name: Deploy backrest
      ansible.builtin.include_role:
        name: deploy_backrest
      vars:
        bkrs_repo_password: '{{ v_kopia_repo_password }}'
        bkrs_rclone_config:
          mailru:
            backup_path: NoSync/Backups/HomeServer/backrest
            webdav_url: https://webdav.cloud.mail.ru
            user: '{{ v_rclone_config.mailru.user }}'
            password_enc: '{{ v_rclone_config.mailru.password_enc }}'
      tags:
        - applications
        - backrest

    - name: Deploy semaphore
      ansible.builtin.include_role:
        name: deploy_semaphore
      vars:
        smph_pg_password: '{{ v_semaphore_pg_password }}'
        smph_admin_password: '{{ v_semaphore_admin_password }}'
        smph_access_key_encryption: '{{ v_semaphore_access_key_encryption }}'
      tags:
        - applications
        - semaphore

    - name: Setup observability
      ansible.builtin.include_role:
        name: setup_observability
      vars:
        obs_docker_root_dir: '{{ g_pools.fast.custom_dirs.docker_root }}'
      tags:
        - applications
        - observability

    - name: Deploy 'portainer'
      ansible.builtin.include_role:
        name: deploy_portainer
      vars:
        prt_app_host: 'portainer.{{ g_duckdns_domain }}'
      tags:
        - applications
        - portainer

    - name: Deploy 'immich'
      ansible.builtin.include_role:
        name: deploy_immich
      vars:
        imch_store_data_path: '{{ g_pools.slow.custom_dirs.apps_data }}'
        imch_db_password: '{{ v_db_passwords.immich }}'
      tags:
        - applications
        - immich

    - name: Deploy 'homepage'
      ansible.builtin.include_role:
        name: deploy_homepage
      tags:
        - applications
        - homepage
