---
- name: Configure the home server
  hosts: homeserver
  vars_files:
    - vars/vault.yml
    - vars/apps.yml
  vars:
    p_host_id: '{{ g_host_ip }}'

    p_timezone: '{{ g_timezone }}'

    p_dirs:
      apps_data_ds: '{{ g_pools.fast.custom_dirs.apps_data_ds }}'
      apps_data: '{{ g_pools.fast.custom_dirs.apps_data }}'
      docker_root: '{{ g_pools.fast.custom_dirs.docker_root }}'
      compose_files: '{{ g_pools.fast.custom_dirs.compose_files }}'
      slow_data: '{{ g_pools.slow.custom_dirs.apps_data  }}'
      slow_data_ds: '{{ g_pools.slow.custom_dirs.apps_data_ds  }}'
      backups_root: '{{ g_pools.slow.custom_dirs.backups_root }}'
      smb_root: '{{ g_pools.slow.custom_dirs.shared }}/shared'

    p_apps_user: '{{ g_apps_user }}'

    p_default_permissions:
      file: '0644'
      directory: '0754'
  tasks:
    - name: Show all facts first
      ansible.builtin.debug:
        var: ansible_facts

    - name: Setup environment
      ansible.builtin.import_tasks: tasks/setup_environment.yml
      tags:
        - server_init

    - name: Deploy backrest
      ansible.builtin.import_role:
        name: deploy_backrest
      vars:
        bkrs_repo_password: '{{ v_backup_repo_password }}'
        bkrs_rclone_config:
          mailru:
            backup_path: NoSync/Backups/HomeServer/backrest
            webdav_url: https://webdav.cloud.mail.ru
            user: '{{ v_rclone_config.mailru.user }}'
            password_enc: '{{ v_rclone_config.mailru.password_enc }}'
          gdrive:
            token_json: '{{ v_rclone_config.gdrive.token_json }}'
      tags:
        - applications
        - backrest

    - name: Setup observability
      ansible.builtin.import_role:
        name: setup_observability
      vars:
        obs_docker_root_dir: '{{ g_pools.fast.custom_dirs.docker_root }}'
      tags:
        - applications
        - observability

    - name: Deploy 'portainer'
      ansible.builtin.import_role:
        name: deploy_portainer
      vars:
        prt_app_host: 'portainer.{{ g_duckdns_domain }}'
      tags:
        - applications
        - portainer

    - name: Deploy 'immich'
      ansible.builtin.import_role:
        name: deploy_immich
      vars:
        imch_db_password: '{{ v_db_passwords.immich }}'
      tags:
        - applications
        - immich

    - name: Deploy 'homepage'
      ansible.builtin.import_role:
        name: deploy_homepage
      tags:
        - applications
        - homepage

    - name: Deploy 'paperless'
      ansible.builtin.import_role:
        name: deploy_paperless
      vars:
        ppls_secretkey: '{{ v_paperless_secretkey }}'
        ppls_app_host: 'paperless.{{ g_duckdns_domain }}'
        ppls_admin_password: '{{ v_paperless_admin_password }}'
      tags:
        - applications
        - paperless

    - name: Deploy 'grist'
      ansible.builtin.import_role:
        name: deploy_grist
      vars:
        grst_app_host: 'grist.{{ g_duckdns_domain }}'
        grst_minio_password: '{{ v_grist_minio_password }}'
      tags:
        - applications
        - grist

    - name: Deploy 'hoarder'
      ansible.builtin.import_role:
        name: deploy_hoarder
      vars:
        hrdr_nextauth_secret: '{{ v_hoarder.nextauth_secret }}'
        hrdr_meili_master_key: '{{ v_hoarder.meili_master_key }}'

        hrdr_api_token: '{{ v_hoarder.api_token }}'
        hrdr_bot_tg_token: '{{ v_hoarder.tg_bot_token }}'
        hrdr_bot_tg_allowlist: '{{ v_hoarder.tg_bot_allowlist }}'
      tags:
        - applications
        - hoarder

    - name: Deploy 'forgejo'
      ansible.builtin.import_role:
        name: deploy_forgejo
      vars:
        frgj_app_host: 'forgejo.{{ g_duckdns_domain }}'
      tags:
        - applications
        - forgejo

    - name: Deploy 'readeck'
      ansible.builtin.import_role:
        name: deploy_readeck
      tags:
        - applications
        - readeck
