---
- name: Configure the home server
  hosts: homeserver
  vars_files:
    - vars/vault.yml
    - vars/apps.yml
  vars:
    p_host_id: '{{ g_ips.homelab }}'

    p_timezone: '{{ g_timezone }}'

    p_dirs:
      apps_data_ds: '{{ g_pools.fast.custom_dirs.apps_data_ds }}'
      apps_data: '{{ g_pools.fast.custom_dirs.apps_data }}'
      docker_root: '{{ g_pools.fast.custom_dirs.docker_root }}'
      compose_files: '{{ g_pools.fast.custom_dirs.compose_files }}'
      slow_data: '{{ g_pools.slow.custom_dirs.apps_data  }}'
      slow_data_ds: '{{ g_pools.slow.custom_dirs.apps_data_ds  }}'
      backups_root: '{{ g_pools.slow.custom_dirs.backups_root }}'
      smb_root: '{{ g_pools.slow.custom_dirs.shared }}/shared'
      media_root: '{{ g_pools.slow.custom_dirs.shared }}/media'

    p_apps_user: '{{ g_apps_user }}'
    p_smb_user: '{{ g_smb_user }}'

    p_default_permissions:
      file: '0644'
      directory: '0754'

    p_base_domain: '{{ g_duckdns_domain }}'
  tasks:
    - name: Show all facts first
      ansible.builtin.debug:
        var: ansible_facts

    - name: Setup environment
      ansible.builtin.import_tasks: tasks/setup_environment.yml
      tags:
        - server_init

    - name: Deploy backrest
      ansible.builtin.import_role:
        name: deploy_backrest
      vars:
        bkrs_repo_password: '{{ v_backup_repo_password }}'
        bkrs_rclone_config:
          mailru:
            backup_path: NoSync/Backups/HomeServer/backrest
            webdav_url: https://webdav.cloud.mail.ru
            user: '{{ v_rclone_config.mailru.user }}'
            password_enc: '{{ v_rclone_config.mailru.password_enc }}'
          gdrive:
            token_json: '{{ v_rclone_config.gdrive.token_json }}'
      tags:
        - applications
        - backrest

    - name: Setup observability
      ansible.builtin.import_role:
        name: setup_observability
      vars:
        obs_docker_root_dir: '{{ g_pools.fast.custom_dirs.docker_root }}'
      tags:
        - applications
        - observability

    - name: Deploy 'portainer'
      ansible.builtin.import_role:
        name: deploy_portainer
      vars:
        prt_app_host: 'portainer.{{ g_duckdns_domain }}'
      tags:
        - applications
        - portainer

    - name: Deploy 'immich'
      ansible.builtin.import_role:
        name: deploy_immich
      vars:
        imch_db_password: '{{ v_db_passwords.immich }}'
      tags:
        - applications
        - immich

    - name: Deploy 'homepage'
      ansible.builtin.import_role:
        name: deploy_homepage
      tags:
        - applications
        - homepage

    - name: Deploy 'paperless'
      ansible.builtin.import_role:
        name: deploy_paperless
      vars:
        ppls_secretkey: '{{ v_paperless_secretkey }}'
        ppls_app_host: 'paperless.{{ g_duckdns_domain }}'
        ppls_admin_password: '{{ v_paperless_admin_password }}'
      tags:
        - applications
        - paperless

    - name: Deploy 'grist'
      ansible.builtin.import_role:
        name: deploy_grist
      vars:
        grst_app_host: 'grist.{{ g_duckdns_domain }}'
        grst_minio_password: '{{ v_grist_minio_password }}'
      tags:
        - applications
        - grist

    - name: Deploy 'hoarder'
      ansible.builtin.import_role:
        name: deploy_hoarder
      vars:
        hrdr_nextauth_secret: '{{ v_hoarder.nextauth_secret }}'
        hrdr_meili_master_key: '{{ v_hoarder.meili_master_key }}'

        hrdr_api_token: '{{ v_hoarder.api_token }}'
        hrdr_bot_tg_token: '{{ v_hoarder.tg_bot_token }}'
        hrdr_bot_tg_allowlist: '{{ v_hoarder.tg_bot_allowlist }}'
      tags:
        - applications
        - hoarder

    - name: Deploy 'linkwarden'
      ansible.builtin.import_role:
        name: deploy_linkwarden
      vars:
        lkw_nextauth_secret: '{{ v_linkwarden.nextauth_secret }}'
        lkw_meili_master_key: '{{ v_linkwarden.meili_master_key }}'
        lkw_postgres_password: '{{ v_linkwarden.postgres_password }}'
      tags:
        - applications
        - linkwarden

    - name: Deploy 'forgejo'
      ansible.builtin.import_role:
        name: deploy_forgejo
      vars:
        frgj_app_host: 'forgejo.{{ g_duckdns_domain }}'
      tags:
        - applications
        - forgejo

    - name: Deploy 'readeck'
      ansible.builtin.import_role:
        name: deploy_readeck
      tags:
        - applications
        - readeck

    - name: Deploy 'wallos'
      ansible.builtin.import_role:
        name: deploy_wallos
      tags:
        - applications
        - wallos

    - name: Deploy 'silverbullet'
      ansible.builtin.import_role:
        name: deploy_silverbullet
      tags:
        - applications
        - silverbullet

    - name: Deploy 'glance'
      ansible.builtin.import_role:
        name: deploy_glance
      vars:
        glnc_todoist_token: '{{ v_glance.todoist_token }}'
      tags:
        - applications
        - glance

    - name: Deploy 'stirling_pdf'
      ansible.builtin.import_role:
        name: deploy_stirling_pdf
      tags:
        - applications
        - stirling_pdf

    - name: Deploy 'planka'
      ansible.builtin.import_role:
        name: deploy_planka
      vars:
        pnk_app_host: 'planka.{{ g_duckdns_domain }}'
        pnk_oidc:
          client_id: '{{ v_planka.oidc_client_id }}'
          client_secret: '{{ v_planka.oidc_client_secret }}'
          issuer: 'authentik.{{ g_duckdns_domain }}'
      tags:
        - applications
        - planka

    - name: Deploy 'opencloud'
      ansible.builtin.import_role:
        name: deploy_opencloud
      vars:
        opcd_collabora_admin_user: '{{ v_admin_login_user.login }}'
        opcd_collabora_admin_password: '{{ v_admin_login_user.password }}'
      tags:
        - applications
        - opencloud

    - name: Deploy 'jellyfin'
      ansible.builtin.import_role:
        name: deploy_jellyfin
      vars:
        jlfn_app_host: 'jellyfin.{{ g_duckdns_domain }}'
      tags:
        - applications
        - jellyfin

    - name: Deploy 'koillection'
      ansible.builtin.import_role:
        name: deploy_koillection
      vars:
        koil_app_secret: '{{ v_koillection.app_secret }}'
        koil_jwt_passphrase: '{{ v_koillection.jwt_passphrase }}'
        koil_db_password: '{{ v_koillection.db_password }}'

        koil_app_host: 'koillection.{{ g_duckdns_domain }}'
      tags:
        - applications
        - koillection
