---
- name: Configure the home server
  hosts: homeserver
  vars_files:
    - vars/vault.yml
    - vars/apps.yml
  vars:
    p_apps_data: '{{ g_pools.fast.custom_dirs.apps_data }}'

    p_apps_user: '{{ g_apps_user }}'

    p_default_permissions:
      file: '0644'
      directory: '0754'
  tasks:
    - name: Setup environment
      ansible.builtin.include_tasks: tasks/setup_environment.yml
      tags:
        - server_init

    - name: Setup observability
      ansible.builtin.include_role:
        name: setup_observability
      vars:
        obs_docker_root_dir: '{{ g_pools.fast.custom_dirs.docker_root }}'
      tags:
        - applications
        - observability

    - name: Deploy 'portainer'
      ansible.builtin.include_role:
        name: deploy_portainer
      vars:
        prt_stack_path: '{{ g_pools.fast.custom_dirs.compose_files }}'
        prt_app_host: 'portainer.{{ g_duckdns_domain }}'
      tags:
        - applications
        - dockge

    - name: Deploy 'immich'
      ansible.builtin.include_role:
        name: deploy_immich
      vars:
        imch_store_data_path: '{{ g_pools.slow.custom_dirs.apps_data }}'
        imch_db_password: '{{ g_db_passwords.immich }}'
      tags:
        - applications
        - immich
