---
collections:
  - name: community.docker
    version: '>=3.8.0'
  - name: vladgh.samba
    version: '>=3.1.1'
  - name: ttafsir.sqlite_utils
    version: '>=1.4.0'
roles:
  - name: artis3n.tailscale
    version: 'v4.5.0'
  - name: darkwizard242.lazydocker
    version: '2.6.1'
