services:
  [appname]:
    image: [appname]:${APP_VERSION}
    container_name: '[appname]'
    hostname: '[appname]'
    user: '${APP_USER}:${APP_GROUP}'
    environment:
      TZ: ${TIMEZONE}
      PUID: ${APP_USER}
      PGID: ${APP_GROUP}
    env_file:
      - .env
    volumes:
      - '${APP_DATA_PATH}/db:...'
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginxnetwork
