---
- name: Start 'portainer'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_data: '{{ prt_apps_data_path }}/portainer'
    t_app_name: 'portainer'
    t_app_user: '{{ prt_app_user.user }}'
    t_app_group: '{{ prt_app_user.group }}'
    t_app_data_dirs:
      - '{{ prt_apps_data_path }}/portainer/data'
