---
- name: Create directories for Nginx Proxy Manager
  ansible.builtin.file:
    path: '{{ dir_path }}'
    state: directory
    owner: '{{ prx_app_user.user }}'
    group: '{{ prx_app_user.group }}'
    recurse: true
    mode: '0754'
  become: true
  loop:
    - '{{ prx_apps_data_path }}/nginx'
    - '{{ prx_apps_data_path }}/nginx/data'
    - '{{ prx_apps_data_path }}/nginx/letsencrypt'
  loop_control:
    loop_var: dir_path

- name: Create a docker network
  community.docker.docker_network:
    name: nginxnetwork

- name: Start 'Nginx Proxy Manager'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_data: '{{ prx_apps_data_path }}/nginx'
    t_app_user: '{{ prx_app_user.user }}'
    t_app_group: '{{ prx_app_user.group }}'
    t_app_data_dirs: []
