---
- name: Install and run 'Tailscale'
  ansible.builtin.import_role:
    name: artis3n.tailscale
  vars:
    tailscale_authkey: "{{ v_tailscale.api_token }}"
  tags:
    - tailscale

- name: Create a docker network
  community.docker.docker_network:
    name: nginxnetwork

- name: Start 'Nginx Proxy Manager'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'nginx'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/nginx'
      - '{{ p_dirs.apps_data }}/nginx/data'
      - '{{ p_dirs.apps_data }}/nginx/letsencrypt'
