---
- name: Create a docker network
  community.docker.docker_network:
    name: nginxnetwork

- name: Start 'Nginx Proxy Manager'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'nginx'
    t_app_data_dirs:
      - '{{ p_apps_data }}/nginx'
      - '{{ p_apps_data }}/nginx/data'
      - '{{ p_apps_data }}/nginx/letsencrypt'
