version: '3.8'
services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    user: ${APP_USER}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=${STACKS_PATH}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_PATH}/data:/app/data
      - ${STACKS_PATH}:${STACKS_PATH}

networks:
  default:
    external: true
    name: nginxnetwork
