---
- name: Create directory for the app's data
  ansible.builtin.file:
    path: '{{ dir_path }}'
    state: directory
    owner: '{{ t_app_user }}'
    group: '{{ t_app_group }}'
    recurse: true
    mode: '0754'
  become: true
  loop: '{{ t_app_data_dirs }}'
  loop_control:
    loop_var: dir_path

- name: Upload compose file
  ansible.builtin.copy:
    src: compose.yml
    dest: '{{ t_app_data }}/compose.yml'
    owner: '{{ t_app_user }}'
    group: '{{ t_app_group }}'
    mode: '0644'
  become: true

- name: Upload env file
  ansible.builtin.template:
    src: .env.j2
    dest: '{{ t_app_data }}/.env'
    owner: '{{ t_app_user }}'
    group: '{{ t_app_group }}'
    mode: '0644'
  become: true

- name: Fetch user's UID
  ansible.builtin.command: 'id -u {{ t_app_user }}'
  changed_when: false
  register: t_tmp_app_data_uid

- name: Fetch user's GID
  ansible.builtin.command: 'id -g {{ t_app_user }}'
  changed_when: false
  register: t_tmp_app_data_gid

- name: Replace user with UID:GID
  ansible.builtin.lineinfile:
    path: '{{ t_app_data }}/.env'
    regexp: '^APP_USER=.*$'
    line: 'APP_USER={{ t_tmp_app_data_uid.stdout }}:{{ t_tmp_app_data_gid.stdout }}'
  become: true

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: '{{ t_app_data }}'
  become: true
  when: ansible_check_mode is false
