---
- name: Add 'gierens' repository
  ansible.builtin.deb822_repository:
    name: gierens
    types: deb
    uris: http://deb.gierens.de
    suites: stable
    components: main
    architectures: amd64
    signed_by: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
    state: present
  become: true

- name: Install 'eza'
  ansible.builtin.apt:
    name: "eza"
    state: present
    update_cache: true
  become: true
