---
- name: Install the nodejs LTS repo
  ansible.builtin.deb822_repository:
    name: nodesource
    types: deb
    uris: "https://deb.nodesource.com/node_{{ t_node_version }}.x"
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs
  ansible.builtin.apt:
    name: nodejs
    state: present
    update_cache: true
