---
- name: Install the gpg key for nodejs LTS
  ansible.builtin.apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ t_node_version }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install the nodejs
  ansible.builtin.apt:
    name: nodejs
    state: present
