---
- name: Start 'semaphore'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'semaphore'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/semaphore/pg_data'
      - '{{ p_dirs.apps_data }}/semaphore/playbooks'
