---
- name: Create directory for the app's data
  ansible.builtin.file:
    path: '{{ dir_path }}'
    state: directory
    owner: '{{ obs_app_user.user }}'
    group: '{{ obs_app_user.group }}'
    recurse: true
    mode: '0644'
  loop:
    - '{{ obs_apps_data_path }}/observability/grafana/data'
    - '{{ obs_apps_data_path }}/observability/loki/config'
    - '{{ obs_apps_data_path }}/observability/loki/data'
    - '{{ obs_apps_data_path }}/observability/prometheus/config'
  loop_control:
    loop_var: dir_path

- name: Start 'Grafana + Prometheus + Loki + cAdvisor'
  ansible.builtin.import_tasks: tasks/compose-up.yml
  vars:
    t_app_data: '{{ obs_apps_data_path }}/observability'
    t_app_user: '{{ obs_app_user.user }}'
    t_app_group: '{{ obs_app_user.group }}'
