---
- name: Check if docker is started
  ansible.builtin.systemd_service:
    name: docker
    state: started
  become: true

- name: Install a Loki login plugin
  community.docker.docker_plugin:
    plugin_name: 'grafana/loki-docker-driver:{{ obs_loki_driver_version }}'
    alias: loki
    state: enable
  become: true

- name: Adjust docker daemon.json to set default logging driver
  ansible.builtin.import_tasks: adjust_docker_daemon.yml

- name: Preconfigure Prometheus
  ansible.builtin.import_tasks: preconfig_prometheus.yml

- name: Preconfigure Loki
  ansible.builtin.import_tasks: preconfig_loki.yml

- name: Start 'Grafana + Prometheus + Loki + cAdvisor'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_data: '{{ obs_apps_data_path }}/observability'
    t_app_user: '{{ obs_app_user.user }}'
    t_app_group: '{{ obs_app_user.group }}'
    t_app_data_dirs:
      - '{{ obs_apps_data_path }}/observability/grafana/data'
      - '{{ obs_apps_data_path }}/observability/prometheus/config'
