---
- name: Create Prometheus user groups
  ansible.builtin.group:
    name: prometheus
    state: present
  become: true

- name: Create Prometheus user
  ansible.builtin.user:
    name: prometheus
    group: prometheus
    groups:
      - '{{ obs_app_user.group }}'
    uid: 65534
    shell: '/sbin/nologin'
    state: present
    append: true
  become: true

- name: Create Prometheus conf directory
  ansible.builtin.file:
    path: '{{ obs_apps_data_path }}/observability/prometheus/config'
    state: directory
    mode: '0644'
    owner: prometheus
    group: prometheus
    recurse: true
  become: true

- name: Copy Prometheus config file
  ansible.builtin.copy:
    src: prometheus.yml
    dest: '{{ obs_apps_data_path }}/observability/prometheus/config/prometheus.yml'
    mode: '0644'
    owner: prometheus
    group: prometheus
  become: true
