---
- name: Create Prometheus conf directory
  ansible.builtin.file:
    path: '{{ obs_apps_data_path }}/observability/prometheus/config'
    state: directory
    mode: '0754'
    owner: '{{ obs_app_user.user }}'
    group: '{{ obs_app_user.group }}'
    recurse: true
  become: true

- name: Copy Prometheus config file
  ansible.builtin.copy:
    src: prometheus.yml
    dest: '{{ obs_apps_data_path }}/observability/prometheus/config/prometheus.yml'
    mode: '0644'
    owner: '{{ obs_app_user.user }}'
    group: '{{ obs_app_user.group }}'
  become: true
