---
- name: Start 'linkwarden'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'linkwarden'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/linkwarden/data'
      - '{{ p_dirs.apps_data }}/linkwarden/cache'
      - '{{ p_dirs.apps_data }}/linkwarden/db'
      - '{{ p_dirs.apps_data }}/linkwarden/meili_data'

# https://github.com/linkwarden/linkwarden/issues/799
#- name: Fix non-root run issues
#  community.docker.docker_container_exec:
#    container: hoarder_app
#    user: root
#    argv:
#      - /bin/sh
#      - "-c"
#      - "{{ item }}"
#  loop:
#    - yarn playwright install
#    - yarn playwright install-deps
