services:
  kopia:
    image: kopia/kopia:${APP_VERSION}
    hostname: kopia
    container_name: kopia
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    user: '0' # root
    restart: unless-stopped
    # Setup the server that provides the web gui
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --without-password # turn off Basic Auth for WebUI
      - --address=0.0.0.0:${APP_PORT}
    env_file:
      - .env
    environment:
      # Set repository password
      KOPIA_PASSWORD: ${REPO_PASSWORD}
      USER: ${APP_USER}
    devices:
      - /dev/fuse:/dev/fuse:rwm
    volumes:
      # Mount local folders needed by kopia
      - ${APP_DATA_PATH}/config:/app/config
      - ${APP_DATA_PATH}/cache:/app/cache
      - ${APP_DATA_PATH}/logs:/app/logs
      - ${APP_DATA_PATH}/rclone:/app/rclone
      # Mount local folders to snapshot
      - /home:/data/host/home:ro
      - /mnt/pools:/data/pools:ro
      # Mount repository location
      - ${REPO_PATH}/repositiory:/repository
      - ${DB_DUMPS_PATH}:/db_dumps:ro
      # Mount path for browsing mounted snaphots
      - ${APP_DATA_PATH}/mounts:/tmp:shared

networks:
  default:
    external: true
    name: nginxnetwork
