---
- name: Start 'planka'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'planka'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/planka/db'
      - '{{ p_dirs.apps_data }}/planka/user-avatars'
      - '{{ p_dirs.apps_data }}/planka/bg-images'
      - '{{ p_dirs.apps_data }}/planka/attachments'
      - '{{ p_dirs.apps_data }}/planka/logs'
