---
- name: Start '[appname]'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: '[appname]'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/[appname]/db'
      - '{{ p_dirs.apps_data }}/[appname]/logos'
