---
- name: Start 'dockge'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_data: '{{ dkg_apps_data_path }}/dockge'
    t_app_user: '{{ dkg_app_user.user }}'
    t_app_group: '{{ dkg_app_user.group }}'
    t_app_data_dirs:
      - '{{ dkg_apps_data_path }}/dockge/data'
