---
- name: Install ZFS
  ansible.builtin.apt:
    name: zfsutils-linux
    state: present
  register: result
  until: result is succeeded

- name: Create zpools
  ansible.builtin.command: >-
    zpool create -m {{ pool.mount_path }} {{ pool.name }} {{ 'mirror' if pool.mirror else '' }} {{ pool.drives }}
  become: true
  loop: '{{ pls_pools }}'
  loop_control:
    loop_var: pool
  changed_when: true

- name: Print created pools
  ansible.builtin.command: zpool list
  become: true
  changed_when: false
