---
- name: Install ZFS
  ansible.builtin.apt:
    name: zfsutils-linux
    state: present
  become: true
  register: result
  until: result is succeeded

- name: Create zpools
  ansible.builtin.include_tasks: tasks/create_pool.yml
  vars:
    pls_t_pool_name: '{{ pool.name }}'
    pls_t_pool_mount_path: '{{ pool.mount_path }}'
    pls_t_pool_mirror: '{{ pool.mirror }}'
    pls_t_pool_drives: '{{ pool.drives }}'
  loop: '{{ pls_pools }}'
  loop_control:
    loop_var: pool

- name: Print created pools
  ansible.builtin.command: zpool list
  become: true
  changed_when: false

- name: Create datasets
  community.general.zfs:
    name: '{{ item }}'
    state: present
  become: true
  loop:
    - '{{ p_dirs.docker_root }}'
    - '{{ p_dirs.apps_data }}'
    - '{{ p_dirs.slow_data }}'
    - '{{ p_dirs.backups_root }}'
  when: false
