---
- name: Create shared folder
  ansible.builtin.file:
    path: '{{ smb_share_root_path }}'
    owner: '{{ smb_samba_user.user }}'
    group: '{{ smb_samba_user.group }}'
    mode: 'u=rwX,g=rwX,o=rX'
    recurse: true
    state: directory

- name: Configure samba
  ansible.builtin.include_role:
    name: vladgh.samba.server
  vars:
    samba_netbios_name: '{{ smb_hostname }}'
    samba_server_string: '{{ smb_hostname }}'
    samba_workgroup: '{{ smb_hostname }}'
    samba_global_include: global-include.conf
    samba_load_homes: false
    samba_load_printers: false
    samba_create_varwww_symlinks: false
    samba_log: /var/log/samba.log
    samba_log_size: 60000
    samba_log_level: '3 passdb:5 auth:10 winbind:2 '
    samba_map_to_guest: Never
    samba_users:
      - name: '{{ smb_samba_user.user }}'
        password: '{{ smb_samba_user.password }}'
    samba_shares_root: '{{ smb_share_root_path }}'
    samba_shares:
      - name: shared
        comment: '{{ smb_hostname }} Shared'
        write_list: '+{{ smb_samba_user.group }}'
        browseable: true
        # Note: When used in the [global] section this parameter may have unwanted side effects.
        # For example: If samba is configured as a MASTER BROWSER (see local master, os level, domain master, preferred master)
        # this option will prevent workstations from being able to browse the network.
        valid_users: '+{{ smb_samba_user.group }}'
