---
- name: Start 'Hoarder'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'hoarder'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/hoarder/data'
      - '{{ p_dirs.apps_data }}/hoarder/meilisearch'
      - '{{ p_dirs.apps_data }}/hoarder/cache/nextjs'
- name: Fix permissions
  community.docker.docker_container_exec:
    container: hoarder_app
    user: root
    argv:
      - /bin/sh
      - "-c"
      - "mkdir -p {{ item }} && chown -R {{ p_apps_user.uid }}:{{ p_apps_user.gid }} {{ item }}"
  loop:
    - /.cache
    - /app
