---
- name: Start 'Hoarder'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'hoarder'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/hoarder/data'
      - '{{ p_dirs.apps_data }}/hoarder/meilisearch'
