---
dcr_docker_user: placeholder

dcr_dirs:
  docker_root: placeholder
  compose_root: placeholder

dcr_arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
  x86_64: amd64
  aarch64: arm64

dcr_lazydocker_version: 0.24.1
