services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:${APP_VERSION}
    container_name: forgejo
    hostname: forgejo
    user: ${APP_USER}:${APP_GROUP}
    environment:
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
    restart: unless-stopped
    volumes:
      - ${APP_DATA_PATH}/data:/var/lib/gitea
      - ${APP_DATA_PATH}/conf:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - forgejo-db

  forgejo-db:
    image: postgres:${PG_VERSION}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=forgejo
      - POSTGRES_DB=forgejo
    volumes:
      - ${APP_DATA_PATH}/postgres:/var/lib/postgresql/data

networks:
  default:
    external: true
    name: nginxnetwork
