---
- name: Start 'wallos'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'wallos'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/wallos/db'
      - '{{ p_dirs.apps_data }}/wallos/logos'
