---
- name: Start 'jellyfin'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'jellyfin'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/jellyfin/config'
      - '{{ p_dirs.apps_data }}/jellyfin/cache'
      - '{{ p_dirs.apps_data }}/jellyfin/fonts'
