services:
  glance:
    image: glanceapp/glance:${APP_VERSION}
    container_name: 'glance'
    hostname: 'glance'
    user: '0' # root because we need to access docker.sock
    environment:
      TZ: ${TIMEZONE}
      PUID: ${APP_USER}
      PGID: ${APP_GROUP}
    env_file:
      - .env
    volumes:
      - '${APP_DATA_PATH}/config:/app/config'
      - '${APP_DATA_PATH}/assets:/app/assets'
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  glance-ext:
    build:
      context: https://github.com/MrModest/glance-extensions.git#b6ed2b52fa33a2f6268cfc81f50ad58191656ef8
      dockerfile: Dockerfile
    container_name: glance-ext
    hostname: glance-ext
    user: ${APP_USER}:${APP_GROUP}
    env_file:
      - .env
    environment:
      APP__PORT: 9999
      TODOIST__FILTER__WORKTODAY: '(Overdue | Today) & (workspace: Work | @💼 WorkTime)'
      TODOIST__FILTER__PRIVATETODAY: '(Overdue | Today) & !workspace: Work'

networks:
  default:
    external: true
    name: nginxnetwork
