- name: Home
  columns:
    - size: small
      widgets:
        - type: group
          widgets:
            - type: extension
              title: To Do
              title-url: https://app.todoist.com/
              cache: 1m
              url: http://glance-ext:9999/todoist
              allow-potentially-dangerous-html: true
              parameters:
                filter: PrivateWeek

            - type: calendar
              first-day-of-week: monday

        - type: server-stats
          hide-header: true
          servers:
            - type: local
              name: HomeServer
              hide-mountpoints-by-default: true
              mountpoints:
                '/host_fs':
                  name: Root
                  hide: false
                '/host_fs/mnt/pools/fast':
                  name: Fast Pool
                  hide: false
                '/host_fs/mnt/pools/slow':
                  name: Slow Pool
                  hide: false

        - type: weather
          location: Berlin, Germany
          units: metric
          hour-format: 24h

        - type: markets
          markets:
            - symbol: DHER.DE
              name: Delivery Hero

        - type: releases
          cache: 1d
          repositories:
            - glanceapp/glance
            - immich-app/immich

    - size: full
      widgets:
        - $include: services.yml

        - type: bookmarks
          title: Links
          groups:
            - links:
                - title: HomeServer
                  url: https://github.com/MrModest/homeserver
                  description: Ansible Playbook
                  icon: di:github-light
            - links:
                - title: Homepage
                  url: https://homepage.mrmodest.duckdns.org
                  description: Old dashboard
                  icon: di:homepage.png

        - type: videos
          channels:
            - UCGKEMK3s-ZPbjVOIuAV8clQ # Core Dumped
            - UC_gKMJFeCf1bKzZr_fICkig # TheDRZJ
            - UCBfZ377Tp-L-YYpAKtpSHcg # HUDAKOV
            - UC5UAwBUum7CPN5buc-_N1Fw # The Linux Experiment

        - type: group
          widgets:
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true
            - type: rss
              limit: 10
              collapse-after: 3
              cache: 12h
              feeds:
                - url: https://selfh.st/rss/
                  title: selfh.st
