- name: Home
  columns:
    - size: small
      widgets:
        - type: group
          widgets:
            - type: extension
              title: To Do
              title-url: https://app.todoist.com/
              cache: 1m
              url: http://glance-ext:9999/todoist
              allow-potentially-dangerous-html: true
              parameters:
                filter: PrivateToday

            - type: calendar
              first-day-of-week: monday

        - type: weather
          location: Berlin, Germany
          units: metric
          hour-format: 24h

        - type: markets
          markets:
            - symbol: DHER.DE
              name: Delivery Hero

        - type: releases
          cache: 1d
          repositories:
            - glanceapp/glance
            - immich-app/immich

        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
              title: selfh.st

    - size: full
      widgets:
        - type: group
          widgets:
            - type: monitor
              cache: 1m
              title: Services
              sites:
                - title: Immich
                  icon: di:immich
                  url: https://immich.mrmodest.duckdns.org
                - title: Paperless
                  icon: di:paperless-ngx
                  url: https://paperless.mrmodest.duckdns.org
                - title: Grist
                  icon: di:grist
                  check-url: http://grist_app:8484/status
                  url: https://grist.mrmodest.duckdns.org
                - title: Forgejo
                  icon: di:forgejo
                  url: https://forgejo.mrmodest.duckdns.org
                - title: Hoarder
                  icon: di:hoarder-light
                  url: https://hoarder.mrmodest.duckdns.org
                - title: Readeck
                  icon: di:readeck
                  url: https://readeck.mrmodest.duckdns.org
                - title: Wallos
                  icon: di:wallos
                  url: https://wallos.mrmodest.duckdns.org
                - title: SilverBullet
                  icon: di:silverbullet
                  url: https://silverbullet.mrmodest.duckdns.org
                - title: OpenCloud
                  icon: di:open-cloud-dark
                  url: https://opencloud.mrmodest.duckdns.org

            - type: hacker-news
            - type: lobsters

        - type: videos
          channels:
            - UCGKEMK3s-ZPbjVOIuAV8clQ # Core Dumped
            - UC_gKMJFeCf1bKzZr_fICkig # TheDRZJ
            - UCBfZ377Tp-L-YYpAKtpSHcg # HUDAKOV

        - type: group
          widgets:
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true
