- type: group
  widgets:
    - type: monitor
      title: Services
      sites:
        - title: Immich
          icon: di:immich
          url: https://immich.modestlab.dev
        - title: Jellyfin
          icon: di:jellyfin
          url: https://jellyfin.modestlab.dev
        - title: Paperless
          icon: di:paperless-ngx
          url: https://paperless.modestlab.dev
        - title: Grist
          icon: di:grist
          check-url: http://grist_app:8484/status
          url: https://grist.modestlab.dev
        - title: Forgejo
          icon: di:forgejo
          url: https://forgejo.modestlab.dev
        - title: Hoarder
          icon: di:hoarder-light
          url: https://hoarder.modestlab.dev
        - title: Readeck
          icon: di:readeck
          url: https://readeck.modestlab.dev
        - title: Wallos
          icon: di:wallos.png
          url: https://wallos.modestlab.dev
        - title: SilverBullet
          icon: di:silverbullet.png
          url: https://silverbullet.modestlab.dev
        - title: OpenCloud
          icon: di:open-cloud-dark
          url: https://opencloud.modestlab.dev
        - title: Planka
          icon: di:planka
          url: https://planka.modestlab.dev
        - title: Stirling PDF
          icon: di:stirling-pdf
          url: https://stirling_pdf.modestlab.dev
        - title: n8n
          icon: di:n8n
          url: https://n8n.modestlab.dev
        - title: Ghostfolio
          icon: di:ghostfolio
          url: https://ghostfolio.modestlab.dev
        - title: Mealie
          icon: di:mealie
          url: https://mealie.modestlab.dev
        - title: ChangeDetection
          icon: di:changedetection
          url: https://changedetection.modestlab.dev
        - title: Home Assistant
          icon: di:home-assistant
          url: https://ha.modestlab.dev
        - title: Tududi
          icon: di:tududi.png
          url: https://tududi.modestlab.dev
    - type: monitor
      title: ServArr
      sites:
        - title: RDT Client
          icon: di:real-debrid
          url: https://rdt-client.modestlab.dev
        - title: Aria2 NG
          icon: di:ariang.png
          url: https://aria-ng.modestlab.dev
        - title: Sonarr
          icon: di:sonarr
          url: https://sonarr.modestlab.dev
        - title: Prowlarr
          icon: di:prowlarr
          url: https://prowlarr.modestlab.dev
    - type: monitor
      title: Maintenance
      sites:
        - title: Nginx
          icon: di:nginx-proxy-manager
          url: https://npm.modestlab.dev
          allow-insecure: true
        - title: Portainer
          icon: di:portainer
          url: https://portainer.modestlab.dev
        - title: Grafana
          icon: di:grafana
          url: https://grafana.modestlab.dev
        - title: Pi-Hole
          icon: di:pi-hole
          url: https://pihole.modestlab.dev/admin/login
          check-url: http://192.168.178.55:80
          alt-status-codes:
            - 403
          allow-insecure: true
        - title: Backrest
          icon: di:backrest-light
          url: https://backrest.modestlab.dev
        - title: Cronicle
          icon: di:cronicle
          url: https://cronicle.modestlab.dev/
        - title: Authentik
          icon: di:authentik
          url: https://authentik.modestlab.dev
