# WARNING: Make sure to use the docker-compose.yml of the current release:
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
# The compose file on main may not be compatible with the latest release.

name: immich
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    container_name: immich_server
    hostname: immich_server
    user: ${APP_USER}:${APP_GROUP}
    restart: 'unless-stopped'
    volumes:
      - ${DATA_PATH}/data:/data
      - ${DATA_PATH}/external:/usr/src/app/external # https://immich.app/docs/guides/external-library/
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    deploy:
      resources:
        limits:
          cpus: '3'
    healthcheck:
      disable: false

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    container_name: immich_machine_learning
    user: ${APP_USER}:${APP_GROUP}
    restart: 'unless-stopped'
    volumes:
      - ${APP_DATA_PATH}/ml/model-cache:/cache
      - ${APP_DATA_PATH}/ml/matplotlib:/usr/src/app/matplotlib
      - ${APP_DATA_PATH}/ml/dot-config:/.config # https://immich.app/docs/FAQ/#how-can-i-run-immich-as-a-non-root-user
      - ${APP_DATA_PATH}/ml/dot-cache:/.cache
    env_file:
      - .env
    deploy: # https://github.com/immich-app/immich/discussions/2368#discussioncomment-5952765
      resources:
        limits:
          cpus: '2'
    healthcheck:
      disable: false

  redis:
    image: docker.io/valkey/valkey:${REDIS_VERSION}
    container_name: immich_redis
    user: ${APP_USER}:${APP_GROUP}
    restart: 'unless-stopped'
    volumes:
      - ${APP_DATA_PATH}/redis:/data
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    image: ghcr.io/immich-app/postgres:${POSTGRES_VERSION}
    container_name: immich_postgres
    user: ${APP_USER}:${APP_GROUP}
    restart: 'unless-stopped'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${APP_DATA_PATH}/db:/var/lib/postgresql/data
    shm_size: 128mb

networks:
  default:
    external: true
    name: nginxnetwork
