# WARNING: Make sure to use the docker-compose.yml of the current release:
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
# The compose file on main may not be compatible with the latest release.

version: '3.8'
name: immich
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    container_name: immich_server
    user: ${APP_USER}
    restart: 'unless-stopped'
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    container_name: immich_microservices
    user: ${APP_USER}
    restart: 'unless-stopped'
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    container_name: immich_machine_learning
    user: ${APP_USER}
    restart: 'unless-stopped'
    volumes:
      - ${MODEL_CACHE_PATH}:/cache
    env_file:
      - .env

  redis:
    image: registry.hub.docker.com/library/redis:${REDIS_VERSION}
    container_name: immich_redis
    user: redis
    restart: 'unless-stopped'

  database:
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:${POSTGRES_VERSION}
    container_name: immich_postgres
    user: ${APP_USER}
    restart: 'unless-stopped'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${PG_DATA_PATH}:/var/lib/postgresql/data

networks:
  default:
    external: true
    name: nginxnetwork
