---
- name: Start 'forgejo'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'forgejo'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/forgejo/data'
      - '{{ p_dirs.apps_data }}/forgejo/config'
      - '{{ p_dirs.apps_data }}/forgejo/postgres'
