services:
  hoarder-app:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION}
    container_name: hoarder_app
    hostname: hoarder_app
    user: ${APP_USER}:${APP_GROUP}
    restart: unless-stopped
    volumes:
      - ${APP_DATA_PATH}/data:/data
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      MAX_ASSET_SIZE_MB: 2048
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:${CHROME_VERSION}
    container_name: hoarder_chrome
    hostname: hoarder_chrome
    user: ${APP_USER}:${APP_GROUP}
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:${MEILISEARCH_VERSION}
    container_name: hoarder_meilisearch
    hostname: hoarder_meilisearch
    user: ${APP_USER}:${APP_GROUP}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ${APP_DATA_PATH}/meilisearch:/meili_data
  hoarderbot:
    image: ghcr.io/madh93/hoarderbot:${HOARDERBOT_VERSION}
    container_name: hoarderbot
    hostname: hoarderbot
    user: ${APP_USER}:${APP_GROUP}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      HOARDERBOT_HOARDER_URL: http://hoarder-app:3000

networks:
  default:
    external: true
    name: nginxnetwork
