services:
  hoarder-app:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION}
    container_name: hoarder_app
    hostname: hoarder_app
    user: ${APP_USER}:${APP_GROUP}
    restart: unless-stopped
    volumes:
      - ${APP_DATA_PATH}/data:/data
      - ${APP_DATA_PATH}/cache/nextjs:/app/apps/web/.next/cache
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      MAX_ASSET_SIZE_MB: 2048
  chrome:
    image: ghcr.io/karakeep-app/karakeep-chrome:${CHROME_VERSION}
    container_name: hoarder_chrome
    hostname: hoarder_chrome
    user: ${APP_USER}:${APP_GROUP}
    restart: unless-stopped
    init: true
    command:
      - --disable-gpu
      - --disable-dev-shm-usage
      - --hide-scrollbars
      - --disable-blink-features=AutomationControlled
      - --window-size=1440,900
  meilisearch:
    image: getmeili/meilisearch:${MEILISEARCH_VERSION}
    container_name: hoarder_meilisearch
    hostname: hoarder_meilisearch
    user: ${APP_USER}:${APP_GROUP}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ${APP_DATA_PATH}/meilisearch:/meili_data
  hoarderbot:
    image: ghcr.io/madh93/karakeepbot:${KARAKEEPBOT_VERSION}
    container_name: hoarderbot
    hostname: hoarderbot
    user: ${APP_USER}:${APP_GROUP}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      KARAKEEPBOT_KARAKEEP_URL: http://hoarder-app:3000

networks:
  default:
    external: true
    name: nginxnetwork
