---
- name: Start 'readeck'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'readeck'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/readeck/data'

- name: Fix permissions
  community.docker.docker_container_exec:
    container: readeck
    user: root
    argv:
      - /bin/sh
      - "-c"
      - "mkdir -p {{ item }} && chown -R {{ p_apps_user.uid }}:{{ p_apps_user.gid }} {{ item }}"
  loop:
    - /readeck
