---
- name: Create conf directory
  ansible.builtin.file:
    path: '{{ p_dirs.apps_data }}/glance/config'
    state: directory
    mode: '{{ p_default_permissions.directory }}'
    owner: '{{ p_apps_user.user }}'
    group: '{{ p_apps_user.group }}'
    recurse: true
  become: true

- name: Copy config files
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ p_default_permissions.file }}'
    owner: '{{ p_apps_user.user }}'
    group: '{{ p_apps_user.group }}'
  become: true
  loop:
    - src: 'glance.yml'
      dest: '{{ p_dirs.apps_data }}/glance/config/glance.yml'
    - src: 'home.yml'
      dest: '{{ p_dirs.apps_data }}/glance/config/home.yml'

- name: Start 'glance'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'glance'
    t_app_data_dirs:
      - '{{ p_dirs.apps_data }}/glance/assets'
