global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: immich_server
    static_configs:
      - targets: ['immich_server:8081']
  - job_name: immich_microservices
    static_configs:
      - targets: ['immich_microservices:8081']
  - job_name: node
    static_configs:
      - targets: ['host.docker.internal:9100']
