---
- name: Start 'kopia'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'kopia'
    t_app_data_dirs:
      - '{{ p_apps_data }}/kopia/config'
      - '{{ p_apps_data }}/kopia/cache'
      - '{{ p_apps_data }}/kopia/logs'
      - '{{ p_apps_data }}/kopia/rclone'
      - '{{ p_apps_data }}/kopia/mounts'
      - '{{ p_backups_root }}/kopia/repositiory'
  tags:
    - kopia

- name: Configure 'rclone'
  ansible.builtin.template:
    src: rclone.conf.j2
    dest: "{{ p_apps_data }}/kopia/rclone/rclone.conf"
    owner: root
    group: root
    mode: 0644
  tags:
    - kopia
