---
- name: Start 'backrest'
  ansible.builtin.import_tasks: tasks/compose_up.yml
  vars:
    t_app_name: 'backrest'
    t_app_data_dirs:
      - '{{ p_apps_data }}/backrest/config'
      - '{{ p_apps_data }}/backrest/cache'
      - '{{ p_apps_data }}/backrest/logs'
      - '{{ p_apps_data }}/backrest/rclone'
      - '{{ p_apps_data }}/backrest/mounts'
      - '{{ p_backups_root }}/backrest/repos'
  tags:
    - backrest

- name: Configure 'rclone'
  ansible.builtin.template:
    src: rclone.conf.j2
    dest: "{{ p_apps_data }}/backrest/rclone/rclone.conf"
    owner: root
    group: root
    mode: '{{ p_default_permissions.file }}'
  become: true
  tags:
    - backrest

- name: Configure 'backrest'
  ansible.builtin.template:
    src: backrest-config.json.j2
    dest: "{{ p_apps_data }}/backrest/config/config.json"
    owner: root
    group: root
    mode: '{{ p_default_permissions.file }}'
  become: true
  tags:
    - backrest
