---
- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400 # One day

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-pip
      - jq
      - bat
      - tree
      - acl # Access Control List
    state: present
  become: true

- name: Setup aliases
  ansible.builtin.copy:
    dest: /etc/profile.d/aliases.sh
    content: |
      alias ll='ls -lah'
      alias sll='sudo ls -lah'
      alias bat='batcat --wrap=never'

      alias docker-start='sudo systemctl start docker'
      alias docker-stop='sudo systemctl stop docker'
      alias docker-restart='sudo systemctl restart docker'
      alias docker-status='sudo systemctl status docker'
      alias d-container-restart='docker container restart'

      alias dcu='docker compose up -d'
      alias dcd='docker compose down'

      alias docker-ps='docker ps | bat'
      alias docker-logs='docker logs -f'

      function docker-sh() {
        docker exec -it $1 sh
      }

      function docker-bash() {
        docker exec -it $1 bash
      }

      function docker-envs() {
        docker exec $1 env
      }
    owner: root
    group: root
    mode: '0644'
  become: true
