---
- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400 # One day

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-pip
      - jq
      - bat
    state: present
  become: true

- name: Setup aliases
  ansible.builtin.copy:
    dest: /etc/profile.d/aliases.sh
    content: |
      alias sll='sudo ls -lah'
      alias bat='batcat'

      alias docker-start='sudo systemctl start docker'
      alias docker-start='sudo systemctl stop docker'
      alias docker-restart='sudo systemctl restart docker'
      alias docker-status='sudo systemctl status docker'
      alias dcu='docker compose up -d'
      alias dcd='docker compose down'
    owner: root
    group: root
    mode: '0644'
  become: true
