---
- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400 # One day

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-pip
      - jq
      - bat
      - tree
      - acl # Access Control List
    state: present
  become: true

- name: Setup aliases
  ansible.builtin.template:
    src: aliases.sh.j2
    dest: /etc/profile.d/aliases.sh
    owner: root
    group: root
    mode: '{{ p_default_permissions.file }}'
  become: true
