services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:${NPM_VERSION}'
    container_name: nginxproxymanager
    hostname: nginxproxymanager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81' # Admin Web Port:
      - '443:443'
    env_file:
      - .env
    volumes:
      - ${APP_DATA}/data:/data
      - ${APP_DATA}/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s

networks:
  default:
    external: true
    name: nginxnetwork
