---
obs_app_user:
  user: placeholder
  group: placeholder
obs_apps_data_path: placeholder
obs_apps_ports:
  grafana: 3000
  loki: 3100
  prometheus: 9092
  cadvisor: 8082
  docker_metrics: 9323
obs_docker_root_dir: /var/lib/docker
